services:
  backend:
    build: ./backend  # Correct path to backend folder
    ports:
      - "5001:3001"  
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-tracker
    depends_on:
      - mongo
    networks:
      - app-network
  frontend:
    build: ./frontend  # Correct path to frontend folder
    ports:
      - "80:80"  # NGINX on port 80, mapped to 3000
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge